import Sidebar from "../../layouts/Sidebar";
import Navbar from "../../layouts/Navbar";

import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
} from "recharts";

const pieData = [
  { name: "Available", value: 42 },
  { name: "Occupied", value: 71 },
  { name: "Reserved", value: 7 },
];

const COLORS = ["#22c55e", "#ef4444", "#facc15"];

const barData = [
  { ward: "Ward A", beds: 30 },
  { ward: "Ward B", beds: 24 },
  { ward: "Ward C", beds: 38 },
  { ward: "Ward D", beds: 28 },
];

function Reports() {

  const downloadReport = () => {

    const report = `
==================================================
            ICU BED MANAGEMENT REPORT
==================================================

Hospital : City Care Hospital

Generated On : ${new Date().toLocaleString()}

--------------------------------------------------
BED SUMMARY
--------------------------------------------------

Total ICU Beds     : 120
Available Beds     : 42
Occupied Beds      : 71
Reserved Beds      : 7

--------------------------------------------------
BEDS BY WARD
--------------------------------------------------

Ward A : 30 Beds
Ward B : 24 Beds
Ward C : 38 Beds
Ward D : 28 Beds

--------------------------------------------------
RECENT ADMISSIONS
--------------------------------------------------

Rahul Kumar     ICU-002    Critical
Priya Sharma    ICU-005    Stable
Arjun Reddy     ICU-011    Recovering

==================================================
Generated by ICU Bed Management System
==================================================
`;

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "ICU_Bed_Report.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-sky-50 via-blue-50 to-white">

      <Sidebar />

      <div className="flex-1">

        <Navbar />

        <div className="p-8">

          <h1 className="text-4xl font-bold text-gray-800">
            Reports
          </h1>

          <p className="text-gray-500 mb-8">
            ICU Bed Utilization & Availability
          </p>

          {/* Summary Cards */}

          <div className="grid md:grid-cols-4 gap-6 mb-8">

            <div className="bg-blue-600 text-white rounded-2xl p-6 shadow-xl">
              <h3>Total Beds</h3>
              <h1 className="text-5xl font-bold mt-3">120</h1>
            </div>

            <div className="bg-green-600 text-white rounded-2xl p-6 shadow-xl">
              <h3>Available</h3>
              <h1 className="text-5xl font-bold mt-3">42</h1>
            </div>

            <div className="bg-red-600 text-white rounded-2xl p-6 shadow-xl">
              <h3>Occupied</h3>
              <h1 className="text-5xl font-bold mt-3">71</h1>
            </div>

            <div className="bg-yellow-500 text-white rounded-2xl p-6 shadow-xl">
              <h3>Reserved</h3>
              <h1 className="text-5xl font-bold mt-3">7</h1>
            </div>

          </div>

          {/* Charts */}

          <div className="grid lg:grid-cols-2 gap-8">

            <div className="bg-white rounded-2xl shadow-lg p-6 h-[400px]">

              <h2 className="text-2xl font-bold mb-4">
                Bed Utilization
              </h2>

              <ResponsiveContainer width="100%" height="90%">

                <PieChart>

                  <Pie
                    data={pieData}
                    dataKey="value"
                    outerRadius={120}
                    label
                  >

                    {pieData.map((entry, index) => (
                      <Cell
                        key={index}
                        fill={COLORS[index]}
                      />
                    ))}

                  </Pie>

                  <Tooltip />

                </PieChart>

              </ResponsiveContainer>

            </div>

            <div className="bg-white rounded-2xl shadow-lg p-6 h-[400px]">

              <h2 className="text-2xl font-bold mb-4">
                Beds by Ward
              </h2>

              <ResponsiveContainer width="100%" height="90%">

                <BarChart data={barData}>

                  <XAxis dataKey="ward" />

                  <YAxis />

                  <Tooltip />

                  <Bar
                    dataKey="beds"
                    fill="#2563eb"
                    radius={[8, 8, 0, 0]}
                  />

                </BarChart>

              </ResponsiveContainer>

            </div>

          </div>

          {/* Recent Admissions */}

          <div className="bg-white rounded-2xl shadow-lg p-6 mt-8">

            <h2 className="text-2xl font-bold mb-5">
              Recent Admissions
            </h2>

            <table className="w-full">

              <thead>

                <tr className="border-b">

                  <th className="text-left py-3">Patient</th>

                  <th className="text-left">Bed</th>

                  <th className="text-left">Ward</th>

                  <th className="text-left">Status</th>

                </tr>

              </thead>

              <tbody>

                <tr className="border-b">

                  <td className="py-4">Rahul Kumar</td>

                  <td>ICU-002</td>

                  <td>A</td>

                  <td className="text-red-600 font-semibold">
                    Critical
                  </td>

                </tr>

                <tr className="border-b">

                  <td className="py-4">Priya Sharma</td>

                  <td>ICU-005</td>

                  <td>B</td>

                  <td className="text-green-600 font-semibold">
                    Stable
                  </td>

                </tr>

                <tr>

                  <td className="py-4">Arjun Reddy</td>

                  <td>ICU-011</td>

                  <td>C</td>

                  <td className="text-blue-600 font-semibold">
                    Recovering
                  </td>

                </tr>

              </tbody>

            </table>

          </div>

          {/* Download Button */}

          <div className="flex justify-end mt-8">

            <button
              onClick={downloadReport}
              className="bg-blue-600 hover:bg-blue-700 hover:scale-105 transition text-white px-8 py-4 rounded-xl shadow-lg text-lg font-semibold"
            >
              📄 Download Report
            </button>

          </div>

        </div>

      </div>

    </div>
  );
}

export default Reports;